services:
  eshop-sql:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: eshop-sql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "@someThingComplicated1234"
      ACCEPT_EULA: "Y"
    restart: unless-stopped
